import {
  METODATA_TITLES,
  METODATA_TITLES_DINAMIC,
} from "../constants/metodata";
import z from "zod";

const envVariablesSchema = z.object({
  BACKEND_URL: z.string(),
  APP_MODE: z.string(),
  REACT_APP_VERSION: z.string(),
  REACT_APP_STATUS: z.string(),
});

const ENV_VARIABLES = envVariablesSchema.parse({
  BACKEND_URL,
  APP_MODE,
  REACT_APP_VERSION,
  REACT_APP_STATUS,
});

export const CONFIG_APP = {
  METODATA_TITLES,
  METODATA_TITLES_DINAMIC,
  API_ENDPOINT: 'http://localhost:8080',
  // API_ENDPOINT: ENV_VARIABLES.BACKEND_URL,
  ACCESS_TOKEN_COOKIE: "ACCESS_TOKEN_BG_LENDING",
  REFRESH_TOKEN_COOKIE: "REFRESH_TOKEN_BG_LENDING",
  PATH_UPLOADS_AVATARS: `${ENV_VARIABLES.BACKEND_URL}/public/uploads/avatars/`,
  PATH_UPLOADS_IMAGES: `${ENV_VARIABLES.BACKEND_URL}/public/uploads/images/`,
  PATH_UPLOADS_PHOTO: `${ENV_VARIABLES.BACKEND_URL}/public/uploads/photos/`,
  START_PAGE_AFTER_LOGIN: "/",
  REACT_APP_VERSION: ENV_VARIABLES.REACT_APP_VERSION,
  REACT_APP_STATUS: ENV_VARIABLES.REACT_APP_STATUS,
  APP_MODE: ENV_VARIABLES.APP_MODE,
} as const;
